### ISSUE TITLE
[Bug]: Completed tasks not hiding

### ISSUE THREAD

**Issue by pianoman723** [RafaelGB/obsidian-db-folder#811]
### Contact Details

pianoman723@gmail.com

### What happened?

I'm just starting to feel my way around using DB Folder, and I've managed to solve most of my issues for myself. The one I still can't figure out is this: no matter what I do, I can't get get the 'Hide completed tasks' option to work. I suspect there's some sort of conflict with another plugin, but I can't seem to isolate it.

![image](https://user-images.githubusercontent.com/30225333/217632880-448b291b-84e3-45f5-92cc-ca97f2741582.png)

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
The problem was with the subtasks. Will be filtered with the next version Commit 6ffdc661

**Comment by pianoman723** [comment]
Hey Rafael, thank you for your attention to this matter. Can you explain what you mean by, "The problem was with the subtasks"? I've updated on both windows and mobile, and don't see any change in behaviour.

**Comment by RafaelGB** [comment]
while I was testing this issue I could reproduce the problem with only subtasks:

- [ ] principal
  - [ ] subtasks

Ans it was resolved with 3.3.2

**Comment by pianoman723** [comment]
Ok I see. Well my original issue persists, should I open another issue or what?

**Comment by RafaelGB** [comment]
If we find what's the reason of your issue I will reopen this one.

code of the filter:
https://github.com/RafaelGB/obsidian-db-folder/blob/f14529049933c0802c41366778dbec38858f4d7c/src/components/cellTypes/TaskCell.tsx#L24

Could you share which plugin you have enabled? We can check if the problem persist with just dataview a dbfolder activated

**Comment by pianoman723** [comment]
Ok thanks. I just went and disabled everything except dataview and dbfolder, restarted Obsidian, and same thing is happening. Anything else I can check?
